# ==== æ¸¸æˆæ–‡æœ¬ ====
team_name:
  red: "<bold><red><shadow:#a0000000>çŠç‘šçº¢</shadow></red></bold>"
  gold: "<bold><gold><shadow:#a0000000>ç¥ç€é‡‘</shadow></gold></bold>"
  yellow: "<bold><yellow><shadow:#a0000000>æŸ æª¬é»„</shadow></yellow></bold>"
  green: "<bold><green><shadow:#a0000000>ç¿¡ç¿ ç»¿</shadow></green></bold>"
  dark_green: "<bold><dark_green><shadow:#a0000000>é’æŸ ç»¿</shadow></dark_green></bold>"
  aqua: "<bold><aqua><shadow:#a0000000>å¤©ç©ºè“</shadow></aqua></bold>"
  blue: "<bold><blue><shadow:#a0000000>æ·±æµ·è“</shadow></blue></bold>"
  light_purple: "<bold><light_purple><shadow:#a0000000>è–°è¡£ç²‰</shadow></light_purple></bold>"

sidebar:
  title: "<shadow:#a0000000><gradient:#ff0000:#EF903E>â€» <bold>ç¦æ­¢äº‹é¡¹</bold> â€»"
  entry:
    name: "{team_name}<white><shadow:#a0aa0000>[<red>â¤</red><white>{life:%02d}]"
    number: "<white><shadow:#a0000000>{criteria}"
  entry_dead:
    name: "<strikethrough>{team_name}<gray><shadow:#a0000000>[ğŸ’”00]"
    number: "<gray><shadow:#a0000000>å·²æ·˜æ±°"

change_team_item_name: "<italic:false><aqua>[<key:key.use>]<yellow>åˆ‡æ¢é˜Ÿä¼"
modify_custom_criteria_item_name: "<italic:false><aqua>[<key:key.use>]<yellow>è®¾ç½®è‡ªå®šä¹‰è¯æ¡"
join_spectator_message: "<yellow>ä½ ç°åœ¨æ˜¯<gray><bold>æ—è§‚è€…"
join_team_message: "<yellow>ä½ åŠ å…¥äº†é˜Ÿä¼ {team_name}"
current_custom_criteria_message: "<yellow>ä½ çš„é˜Ÿä¼çš„è‡ªå®šä¹‰è¯æ¡ï¼š<white>{name}"
self_set_custom_criteria_message: "<yellow>å·²å°†è‡ªå®šä¹‰è¯æ¡è®¾ç½®ä¸ºï¼š<white>{name}"
other_set_custom_criteria_message: "<yellow>{player}å°†è‡ªå®šä¹‰è¯æ¡è®¾ç½®ä¸ºï¼š<white>{name}"
not_set_custom_criteria_message: "<yellow>ä½ çš„é˜Ÿä¼å°šæœªè®¾ç½®è‡ªå®šä¹‰è¯æ¡"
self_remove_custom_criteria_message: "<yellow>å·²å–æ¶ˆè‡ªå·±é˜Ÿä¼å®šä¹‰çš„è‡ªå®šä¹‰è¯æ¡"
other_remove_custom_criteria_message: "<yellow>{player}å–æ¶ˆäº†ä½ çš„é˜Ÿä¼å®šä¹‰çš„è‡ªå®šä¹‰è¯æ¡"
enter_prepare_message: "<yellow>è¯·ä½¿ç”¨æ‰‹ä¸Šçš„ç‰©å“<green><bold>é€‰æ‹©é˜Ÿä¼</bold><yellow>ï¼Œç„¶åè®¾ç½®<green><bold>è‡ªå®šä¹‰è¯æ¡"

modify_custom_criteria:
  title: "<aqua><bold>è®¾ç½®è‡ªå®šä¹‰è¯æ¡"
  body:
    - "<white>åœ¨ä¸‹æ–¹çš„æ–‡æœ¬æ¡†ä¿®æ”¹è‡ªå®šä¹‰è¯æ¡å†…å®¹"
    - "<white>ç„¶åç‚¹å‡»â€œç¡®è®¤â€æŒ‰é’®ä»¥ä¿å­˜ä¿®æ”¹"
    - "<white>ç•™ç©ºä»£è¡¨å–æ¶ˆè‡ªå·±é˜Ÿä¼å®šä¹‰çš„è‡ªå®šä¹‰è¯æ¡"
    - ""
  text_box_title: "<yellow>è‡ªå®šä¹‰è¯æ¡å†…å®¹"
  no_button_label: "<white>å–æ¶ˆ"
  yes_button_label: "<white>ç¡®è®¤"

criteria_command:
  failed:
    game_not_start: "æ¸¸æˆå°šæœªå¼€å§‹"
    invalid_team_name: "ç©å®¶%så·²æ·˜æ±°æˆ–è€…æ˜¯æ—è§‚è€…"
    guess_self_criteria: "ä¸å…è®¸è‡ªå·±æ ‡è®°è‡ªå·±é˜Ÿä¼çŒœä¸­äº†è¯æ¡"

# ç‰©å“
join_team_item:
  red: red_wool
  gold: orange_wool
  yellow: yellow_wool
  green: lime_wool
  dark_green: green_wool
  aqua: light_blue_wool
  blue: blue_wool
  light_purple: magenta_wool
spectator_item: light_gray_wool
modify_custom_criteria_item: writable_book

# ==== å„æ–¹å—ç”Ÿæˆé…ç½® ====
# å®‰å±±å²©ç”Ÿæˆ
andesite_generation:
  # æ·±åº¦èŒƒå›´ï¼Œå¿…é¡»æ˜¯æ•´æ•°èŒƒå›´ã€‚è‹¥ä¸åŒé¡¹çš„èŒƒå›´æœ‰é‡åˆï¼Œåˆ™ä¼˜å…ˆä½¿ç”¨é å‰çš„é¡¹
  - depth: 1..10
    # ç”Ÿæˆæ¯”ä¾‹
    ratio: 0.75
# ç…¤çŸ¿çŸ³ç”Ÿæˆ
coal_ore_generation:
  - depth: 1..3
    ratio: 0.10
  - depth: 4..7
    ratio: 0.07
  - depth: 8..10
    ratio: 0.02
# é“çŸ¿çŸ³ç”Ÿæˆ
iron_ore_generation:
  - depth: 4..7
    ratio: 0.02
  - depth: 8..10
    ratio: 0.05
# é’»çŸ³çŸ¿çŸ³ç”Ÿæˆ
diamond_ore_generation:
  - depth: 8..10
    ratio: 0.01
# åŸºå²©æ·±åº¦
bedrock_depth: 11



# ==== å¯åœ¨æ¸¸æˆå†…åŠ¨æ€é…ç½®çš„é¡¹ ====
# æ¸¸æˆåŒºåŸŸå¤§å°
game_area_size: 65
# æœ€å¤§è§„åˆ™æ•°é‡ï¼ˆé˜Ÿä¼è¡€é‡ï¼‰
life_count: 10
# å¸¸è§„æ¨¡å¼ä¸‹ï¼Œè·å–é’»çŸ³æ—¶çš„è¡Œä¸ºï¼Œå¯ä»¥æ˜¯reduce_others_lifeæˆ–add_self_life
# reduce_others_life: å‡å°‘å…¶ä»–é˜Ÿä¼1ç‚¹ç”Ÿå‘½å€¼
# add_self_life: å¢åŠ è‡ªå·±é˜Ÿä¼1ç‚¹ç”Ÿå‘½å€¼
diamond_behavior: reduce_others_life
