# ==== æ¸¸æˆæ–‡æœ¬ ====
team_name:
  red: "<bold><red><shadow:#a0000000>çº¢é˜Ÿ</shadow></red></bold>"
  gold: "<bold><gold><shadow:#a0000000>æ©™é˜Ÿ</shadow></gold></bold>"
  yellow: "<bold><yellow><shadow:#a0000000>é»„é˜Ÿ</shadow></yellow></bold>"
  green: "<bold><green><shadow:#a0000000>ç»¿é˜Ÿ</shadow></green></bold>"
  aqua: "<bold><aqua><shadow:#a0000000>è“é˜Ÿ</shadow></aqua></bold>"
  dark_aqua: "<bold><dark_aqua><shadow:#a0000000>é’é˜Ÿ</shadow></dark_aqua></bold>"
  light_purple: "<bold><light_purple><shadow:#a0000000>ç²‰é˜Ÿ</shadow></light_purple></bold>"
  dark_purple: "<bold><dark_purple><shadow:#a0000000>ç´«é˜Ÿ</shadow></dark_purple></bold>"

change_team_item_name: "<italic:false><aqua>[<key:key.use>]<yellow>åˆ‡æ¢é˜Ÿä¼"
modify_custom_criteria_item_name: "<italic:false><aqua>[<key:key.use>]<yellow>è®¾ç½®è‡ªå®šä¹‰è¯æ¡"
start_game_item_name: "<italic:false><aqua>[<key:key.use>]<gold>å¼€å§‹æ¸¸æˆï¼"

custom_criteria_name_prefix: "[è‡ªå®šä¹‰]"
diamond_behavior_description:
  reduce_others_life: "å‡å°‘å…¶ä»–é˜Ÿä¼1ç‚¹ç”Ÿå‘½å€¼"
  add_self_life: "å¢åŠ è‡ªå·±é˜Ÿä¼1ç‚¹ç”Ÿå‘½å€¼"

# å‡†å¤‡é˜¶æ®µçš„æ¶ˆæ¯
join_spectator_message: "<yellow>ä½ ç°åœ¨æ˜¯<gray><bold>æ—è§‚è€…"
join_team_message: "<yellow>ä½ åŠ å…¥äº†é˜Ÿä¼ {team_name}"
current_custom_criteria_message: "<yellow>ä½ çš„é˜Ÿä¼çš„è‡ªå®šä¹‰è¯æ¡ï¼š<white>{name}"
self_set_custom_criteria_message: "<yellow>å·²å°†è‡ªå®šä¹‰è¯æ¡è®¾ç½®ä¸ºï¼š<white>{name}"
other_set_custom_criteria_message: "<yellow>{player}å°†è‡ªå®šä¹‰è¯æ¡è®¾ç½®ä¸ºï¼š<white>{name}"
not_set_custom_criteria_message: "<yellow>ä½ çš„é˜Ÿä¼å°šæœªè®¾ç½®è‡ªå®šä¹‰è¯æ¡"
self_remove_custom_criteria_message: "<yellow>å·²å–æ¶ˆè‡ªå·±é˜Ÿä¼å®šä¹‰çš„è‡ªå®šä¹‰è¯æ¡"
other_remove_custom_criteria_message: "<yellow>{player}å–æ¶ˆäº†ä½ çš„é˜Ÿä¼å®šä¹‰çš„è‡ªå®šä¹‰è¯æ¡"
enter_prepare_message: "<yellow>è¯·ä½¿ç”¨æ‰‹ä¸Šçš„ç‰©å“<green><bold>é€‰æ‹©é˜Ÿä¼</bold><yellow>ï¼Œç„¶åè®¾ç½®<green><bold>è‡ªå®šä¹‰è¯æ¡"

# æ¸¸æˆåˆ‡æ¢é˜¶æ®µçš„æ¶ˆæ¯
start_game_message: "<green><bold>æ¸¸æˆå¼€å§‹ï¼"
end_game_message:
  announce: "{team_name} <gold>è·å¾—èƒœåˆ©"
  title: "{team_name}"
  subtitle: "<gold>è·å¾—èƒœåˆ©"
draw_game_message: "<red>æ— äººè·èƒœ"
reset_game_message: "<yellow>æ¸¸æˆå·²é‡ç½®"

# è§¦å‘æ¬¡æ•°ç»Ÿè®¡
trigger_count_message:
  head: "<gray>=====<yellow>è§¦å‘æ¬¡æ•°<gray>====="
  body: "{player}<white>: <green>{count}"
  tail: "<gray>================"

# æ¸¸æˆè¿›è¡Œæ—¶çš„æ¶ˆæ¯
ingame_actionbar: "<green>è·ç¦»æ›´æ¢è¯æ¡è¿˜æœ‰ï¼š<red>{time}ç§’  <green>å‰©ä½™è§„åˆ™æ•°é‡ï¼š<red>{life_count}"
criteria_triggered_message:
  announce: "{who_triggered} <gold>è§¦å‘äº†è§„åˆ™ {criteria}"
  title: "{criteria}"
  subtitle: "{who_triggered} <gold>è§¦å‘äº†è§„åˆ™"
auto_change_criteria_message:
  announce: "{team_name} <yellow>æ›´æ¢äº†è¯æ¡ï¼Œä¸Šä¸€ä¸ªè¯æ¡æ˜¯ï¼š{criteria}"
  title: "è¯æ¡æ›´æ¢"
  subtitle: "<yellow>ä¸Šä¸€ä¸ªè¯æ¡ï¼š{criteria}"
get_diamond_message: "{player} <yellow>è·å¾—äº† <aqua>é’»çŸ³"
holding_custom_criteria_message: "{team_name} <yellow>æ‹¥æœ‰è‡ªå®šä¹‰è§„åˆ™ ã€{criteria}<yellow>ã€‘"
holding_custom_criteria_click_message: "<dark_aqua><hover:show_text:'<aqua>ç‚¹å‡»è§¦å‘'>ã€è§¦å‘è§„åˆ™ç‚¹è¿™é‡Œã€‘"
guess_hint_message: "<yellow>è¾“å…¥<light_purple><hover:show_text:'<aqua>ç‚¹å‡»å¡«å…¥èŠå¤©æ¡†'><click:suggest_command:/criteria guess>/criteria guess \\<ç©å®¶å\\> \\<æ˜¯å¦çŒœä¸­\\></click></hover> <yellow>æ¥æ ‡è®°ç©å®¶æ˜¯å¦çŒœä¸­è¯æ¡"
guess_cooldown_finished_message: "{team_name} <yellow>ç°åœ¨å¯ä»¥çŒœè¯æ¡äº†"
guessed_message:
  success:
    announce: "{player} <yellow>çŒœä¸­äº†è¯æ¡ï¼Œå‰©ä½™è§„åˆ™æ•°<green>+{life_count}<yellow>ï¼Œä¸Šä¸€ä¸ªè¯æ¡æ˜¯ï¼š{criteria}"
    title: "è¯æ¡æ›´æ¢"
    subtitle: "<yellow>çŒœä¸­è¯æ¡ï¼Œå‰©ä½™è§„åˆ™æ•°<green>+{life_count}"
  failed:
    announce: "{player} <red>çŒœé”™äº†è¯æ¡ï¼Œå‰©ä½™è§„åˆ™æ•°<dark_red>-{life_count}<red>ï¼Œä¸Šä¸€ä¸ªè¯æ¡æ˜¯ï¼š{criteria}"
    title: "è¯æ¡æ›´æ¢"
    subtitle: "<red>çŒœé”™è¯æ¡ï¼Œå‰©ä½™è§„åˆ™æ•°<dark_red>-{life_count}"
eliminated_message:
  announce: "{team_name} <dark_red>å·²æ·˜æ±°"
  title: "{team_name}"
  subtitle: "<dark_red>å·²æ·˜æ±°"

# ä¾§è¾¹æ 
sidebar:
  title: "<shadow:#a0000000><gradient:#ff0000:#EF903E>â€» <bold>ç¦æ­¢äº‹é¡¹</bold> â€»"
  entry:
    name: "{team_name}<white><shadow:#a0aa0000>[<red>â¤</red><white>{life_count:%02d}]"
    number: "<yellow><shadow:#a0000000>{criteria}"
    number_winner: "<gold><shadow:#a0000000>è·èƒœè€…"
  entry_dead:
    name: "<strikethrough>{team_name}<gray><shadow:#a0000000>[ğŸ’”00]"
    number: "<gray><shadow:#a0000000>å·²æ·˜æ±°"

# è®¾ç½®è‡ªå®šä¹‰è¯æ¡ç•Œé¢çš„æ–‡æœ¬
modify_custom_criteria:
  title: "<aqua><bold>è®¾ç½®è‡ªå®šä¹‰è¯æ¡"
  body:
    - "<white>åœ¨ä¸‹æ–¹çš„æ–‡æœ¬æ¡†ä¿®æ”¹è‡ªå®šä¹‰è¯æ¡å†…å®¹"
    - "<white>ç„¶åç‚¹å‡»â€œç¡®è®¤â€æŒ‰é’®ä»¥ä¿å­˜ä¿®æ”¹"
    - "<white>ç•™ç©ºä»£è¡¨å–æ¶ˆè‡ªå·±é˜Ÿä¼å®šä¹‰çš„è‡ªå®šä¹‰è¯æ¡"
    - ""
  text_box_title: "<yellow>è‡ªå®šä¹‰è¯æ¡å†…å®¹"
  no_button_label: "<white>å–æ¶ˆ"
  yes_button_label: "<white>ç¡®è®¤"

# /criteriaå‘½ä»¤çš„æ–‡æœ¬
criteria_command:
  failed:
    game_not_start: "æ¸¸æˆå°šæœªå¼€å§‹"
    guess_not_enabled: "çŒœè¯æ¡ç©æ³•æœªå¼€å¯"
    invalid_player: "ç©å®¶%så·²æ·˜æ±°æˆ–è€…æ˜¯æ—è§‚è€…"
    not_custom_criteria: "é˜Ÿä¼%så½“å‰çš„è¯æ¡ä¸æ˜¯è‡ªå®šä¹‰è¯æ¡"
    invalid_team_name: "é˜Ÿä¼%sä¸å­˜åœ¨æˆ–å·²æ·˜æ±°"
    guess_self_criteria: "ä¸å…è®¸è‡ªå·±æ ‡è®°è‡ªå·±çŒœä¸­äº†è¯æ¡"
    guess_in_cooldown: "ç©å®¶%sæ‰€åœ¨é˜Ÿä¼æ­£åœ¨çŒœè¯æ¡å†·å´ä¸­ï¼ˆå‰©ä½™æ—¶é—´ï¼š%dï¼‰"

# ç‰©å“
join_team_item:
  red: red_wool
  gold: orange_wool
  yellow: yellow_wool
  green: lime_wool
  aqua: light_blue_wool
  dark_aqua: cyan_wool
  light_purple: pink_wool
  dark_purple: purple_wool
spectator_item: light_gray_wool
modify_custom_criteria_item: writable_book
start_game_item: nether_star

# ==== å„æ–¹å—ç”Ÿæˆé…ç½® ====
# å®‰å±±å²©ç”Ÿæˆ
andesite_generation:
  # æ·±åº¦èŒƒå›´ï¼Œå¿…é¡»æ˜¯æ•´æ•°èŒƒå›´ã€‚è‹¥ä¸åŒé¡¹çš„èŒƒå›´æœ‰é‡åˆï¼Œåˆ™ä¼˜å…ˆä½¿ç”¨é å‰çš„é¡¹
  - depth: 1..10
    # ç”Ÿæˆæ¯”ä¾‹
    ratio: 0.75
# ç…¤çŸ¿çŸ³ç”Ÿæˆ
coal_ore_generation:
  - depth: 1..3
    ratio: 0.10
  - depth: 4..7
    ratio: 0.07
  - depth: 8..10
    ratio: 0.02
# é“çŸ¿çŸ³ç”Ÿæˆ
iron_ore_generation:
  - depth: 4..7
    ratio: 0.02
  - depth: 8..10
    ratio: 0.05
# é’»çŸ³çŸ¿çŸ³ç”Ÿæˆ
diamond_ore_generation:
  - depth: 8..10
    ratio: 0.01
# åŸºå²©æ·±åº¦
bedrock_depth: 11

# ==== æ¸¸æˆç©æ³•ç›¸å…³çš„é…ç½®é¡¹ ====
# æ˜¯å¦å¯ç”¨æœ‰å…³Yé«˜åº¦çš„è¯æ¡
y_level_criteria_enabled: false
# è‡ªåŠ¨åˆ‡æ¢è¯æ¡çš„æ—¶é—´ï¼Œå¿…é¡»æ˜¯æ•´æ•°ï¼ˆå•ä½ï¼šç§’ï¼‰
auto_change_criteria_time: 120


# ==== å¯åœ¨æ¸¸æˆå†…åŠ¨æ€é…ç½®çš„é¡¹ ====
# æ¸¸æˆåŒºåŸŸå¤§å°
game_area_size: 65
# æœ€å¤§è§„åˆ™æ•°é‡ï¼ˆé˜Ÿä¼è¡€é‡ï¼‰
life_count: 15
# å¸¸è§„æ¨¡å¼ä¸‹ï¼Œè·å–é’»çŸ³æ—¶çš„è¡Œä¸ºï¼Œå¯ä»¥æ˜¯reduce_others_lifeæˆ–add_self_life
# reduce_others_life: å‡å°‘å…¶ä»–é˜Ÿä¼1ç‚¹ç”Ÿå‘½å€¼
# add_self_life: å¢åŠ è‡ªå·±é˜Ÿä¼1ç‚¹ç”Ÿå‘½å€¼
diamond_behavior: reduce_others_life
# æ˜¯å¦å¯ç”¨é’»çŸ³è¡Œä¸º
diamond_behavior_enabled: true
# é’»çŸ³è¡Œä¸ºç¦ç”¨é˜ˆå€¼ï¼Œå½“ä»»æ„ä¸€åç©å®¶ç”Ÿå‘½å€¼è¾¾åˆ°é˜ˆå€¼åŠä»¥ä¸‹æ—¶ï¼Œé’»çŸ³è¡Œä¸ºå°†ç¦ç”¨
# æ­¤é¡¹é…ç½®ä»…åœ¨diamond_behaviorä¸ºreduce_others_lifeæ—¶æœ‰æ•ˆ
diamond_behavior_disabled_threshold: 7
# æ˜¯å¦å…è®¸å„é˜Ÿä¼äººæ•°ä¸å¹³è¡¡
allow_unbalanced_teams: false
# æ˜¯å¦å…è®¸çŒœè¯æ¡
allow_guess_criteria: true
# çŒœä¸­è¯æ¡å¢åŠ çš„ç”Ÿå‘½å€¼
guess_success_add_life: 1
# çŒœé”™è¯æ¡å‡å°‘çš„è§„åˆ™æ•°
guess_failed_reduce_life: 2
