team_name:
  black: é»‘è‰²
  dark_blue: æ·±è“è‰²
  dark_green: æ·±ç»¿è‰²
  dark_aqua: é’è‰²
  dark_red: æ·±çº¢è‰²
  dark_purple: ç´«è‰²
  gold: æ©™è‰²
  dark_gray: æ·±ç°è‰²
  blue: è“è‰²
  green: ç»¿è‰²
  aqua: æµ…è“
  red: çº¢è‰²
  light_purple: å“çº¢è‰²
  yellow: é»„è‰²
  white: ç™½è‰²

sidebar_title: <gradient:#ff0000:#EF903E>â€» <bold>ç¦æ­¢äº‹é¡¹</bold> â€»
sidebar_entry:
  name: <bold>{team_name}</bold><red>[â¤{life:%02d}]
  number: <white>{criteria}
sidebar_entry_dead:
  name: <strikethrough><bold>{team_name}</bold><gray>[ğŸ’”00]</strikethrough>
  number: <gray>å·²æ·˜æ±°

default_life_count: 10
