team_name:
  dark_red: <bold><dark_red><shadow:#a0000000>ç»¯æ¨±çº¢</shadow></dark_red></bold>
  red: <bold><red><shadow:#a0000000>çŠç‘šçº¢</shadow></red></bold>
  gold: <bold><gold><shadow:#a0000000>ç¥ç€é‡‘</shadow></gold></bold>
  yellow: <bold><yellow><shadow:#a0000000>æŸ æª¬é»„</shadow></yellow></bold>
  green: <bold><green><shadow:#a0000000>ç¿¡ç¿ ç»¿</shadow></green></bold>
  dark_green: <bold><dark_green><shadow:#a0000000>é’æŸ ç»¿</shadow></dark_green></bold>
  dark_aqua: <bold><dark_aqua><shadow:#a0000000>ç¢§æ¶›é’</shadow></dark_aqua></bold>
  aqua: <bold><aqua><shadow:#a0000000>å¤©ç©ºè“</shadow></aqua></bold>
  dark_blue: <bold><dark_blue><shadow:#a0000000>æ·±æµ·è“</shadow></dark_blue></bold>
  blue: <bold><blue><shadow:#a0000000>æ˜Ÿç©ºè“</shadow></blue></bold>
  dark_purple: <bold><dark_purple><shadow:#a0000000>æš®éœç´«</shadow></dark_purple></bold>
  light_purple: <bold><light_purple><shadow:#a0000000>è–°è¡£ç²‰</shadow></light_purple></bold>
team_item:
  dark_red: brown_wool
  red: red_wool
  gold: orange_wool
  yellow: yellow_wool
  green: lime_wool
  dark_green: green_wool
  dark_aqua: cyan_wool
  aqua: light_blue_wool
  dark_blue: blue_wool
  blue: purple_wool
  dark_purple: magenta_wool
  light_purple: pink_wool

sidebar_title: <shadow:#a0000000><gradient:#ff0000:#EF903E>â€» <bold>ç¦æ­¢äº‹é¡¹</bold> â€»
sidebar_entry:
  name: {team_name}<white><shadow:#a0aa0000>[<red>â¤</red><white>{life:%02d}]
  number: <white><shadow:#a0000000>{criteria}
sidebar_entry_dead:
  name: <strikethrough>{team_name}<gray><shadow:#a0000000>[ğŸ’”00]
  number: <gray><shadow:#a0000000>å·²æ·˜æ±°

default_life_count: 10
